### ISSUE TITLE
Run-script fails for scripts that include quotation marks

### ISSUE THREAD

**Issue by Martin4Kansas** [CheckPointSW/cpAnsible#16]
I am trying to run the following playbook:

---
- hosts: "localhost"
  vars_files:
  - r80_vars.yml
  tasks:  
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        port: 8443
        domain: System Data
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: "Check Core Dumps"
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: Check Core Dumps
        script: clish -c 'show core-dump status'
        targets: "{{target_firewall}}"
      session-data: "{{login_response}}"

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"

I get the following result using verbosity 3:

TASK [Check Core Dumps] *********************************************************************************************************************
task path: /mnt/c/Users/jm62602/Documents/CheckMates_Aug15_Demos/Ansible-R80-Scripts/GoldenImageScan.yml:18
Using module file /home/jordanmartin/lib/check_point_mgmt/check_point_mgmt.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansible/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<127.0.0.1> (0, '/home/jordanmartin\n', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansible/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365 `" && echo ansible-tmp-1531854944.83-25136561340365="` echo /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365 `" ) && sleep 0'"'"''
<127.0.0.1> (0, 'ansible-tmp-1531854944.83-25136561340365=/home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365\n', '')
<127.0.0.1> PUT /tmp/tmpYlRoGn TO /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/check_point_mgmt.py
<127.0.0.1> SSH: EXEC sshpass -d13 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansible/cp/8239a62529 '[127.0.0.1]'
<127.0.0.1> (0, 'sftp> put /tmp/tmpYlRoGn /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/check_point_mgmt.py\n', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansible/cp/8239a62529 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/ /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/check_point_mgmt.py && sleep 0'"'"''
<127.0.0.1> (0, '', '')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: jordanmartin
<127.0.0.1> SSH: EXEC sshpass -d13 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=jordanmartin -o ConnectTimeout=10 -o ControlPath=/home/jordanmartin/.ansible/cp/8239a62529 -tt 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python /home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/check_point_mgmt.py; rm -rf "/home/jordanmartin/.ansible/tmp/ansible-tmp-1531854944.83-25136561340365/" > /dev/null 2>&1 && sleep 0'"'"''
<127.0.0.1> (0, 'Traceback (most recent call last):\r\n  File "/tmp/ansible_WCvZIz/ansible_module_check_point_mgmt.py", line 250, in <module>\r\n    main()\r\n  File "/tmp/ansible_WCvZIz/ansible_module_check_point_mgmt.py", line 131, in main\r\n    parameters = json.loads(parameters)\r\n  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads\r\n    return _default_decoder.decode(s)\r\n  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode\r\n    obj, end = self.scan_once(s, idx)\r\nValueError: Expecting property name: line 1 column 2 (char 1)\r\n', 'Shared connection to 127.0.0.1 closed.\r\n')
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_WCvZIz/ansible_module_check_point_mgmt.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_WCvZIz/ansible_module_check_point_mgmt.py\", line 131, in main\r\n    parameters = json.loads(parameters)\r\n  File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode\r\n    obj, end = self.scan_once(s, idx)\r\nValueError: Expecting property name: line 1 column 2 (char 1)\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}

Any insights or examples would be great.  Thanks!

**Comment by chkp-rdecker** [comment]
Hi,
I'll check this and get back to you on how this problem can be overcomed.

**Comment by chkp-rdecker** [comment]
Fixed.
The correct YML format to be used:
_script: 'clish -c \"show core-dump status\"'_

**Comment by chkp-rdecker** [comment]
something is wrong with this editor!!!
trying again:
script: 'clish -c \"show core-dump status\"'

**Comment by chkp-rdecker** [comment]
`script: 'clish -c \"show core-dump status\"'`

**Comment by chkp-rdecker** [comment]
ok. succeded to paste the correct format.

**Comment by Martin4Kansas** [comment]
I'm still getting the same error.. 
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_FLBdjL/ansible_module_check_point_mgmt.py\", line 251, in <module>\r\n    main()\r\n  File \"/tmp/ansible_FLBdjL/ansible_module_check_point_mgmt.py\", line 129, in main\r\n    parameters = json.loads(parameters.replace(\"'\", '\"'))\r\n  File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode\r\n    obj, end = self.scan_once(s, idx)\r\nValueError: Expecting , delimiter: line 1 column 86 (char 85)\r\n", "msg": "MODULE FAILURE", "rc": 0}

**Comment by Martin4Kansas** [comment]
I'd like to add that I haven't been able to get a single run-script command to work, even a simple ls command.  This is the output of that:
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Command 'run-script {u'script-name': u'List files', u'targets': u'{{{target name}}}', u'script': u'ls'}' failed with error message: Requested object [{{{target name}}}] not found. All changes are discarded and the session is invalidated."}
Making the same command with the same parameters works in postman though.

**Comment by Martin4Kansas** [comment]
My apologies, I didn't realize @chkp-rdecker had made a change.  There is no longer a problem with quotation marks.  I will open a separate issue with run-script in general.  Thanks @chkp-rdecker!

**Comment by Martin4Kansas** [comment]
The quotation marks are being passed, but unfortunately the calls are still failing.

**Comment by chkp-rdecker** [comment]
can you paste here the output of what is failing?

**Comment by Martin4Kansas** [comment]
```
---
- hosts: "localhost"
  vars_files:
  - r80_vars.yml
  tasks:  
  - name: "Login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        port: 8443
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: "Create output file"
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: "Create output file"
        script: "touch output.txt"
        targets: "{{targets}}"
      session-data: "{{login_response}}"
      
  - name: "Golden Image"
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: "Golden Image"
        script: 'clish -c \"show core-dump status\" &>> output.txt'
        targets: "{{targets}}"
      session-data: "{{login_response}}"
    #Core dumps enabled
```

```
PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [127.0.0.1]

TASK [Login] ***********************************************************************************************************
ok: [127.0.0.1]

TASK [Create output file] **********************************************************************************************
ok: [127.0.0.1]

TASK [Golden Image] ****************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Command 'run-script {u'script-
name': u'Golden Image', u'targets': u'{{myTarget}}', u'script': u\"clish -c 'show core-dump
status' &>> output.txt\"}' failed. All changes are discarded and the session is invalidated."}
        to retry, use: --limit @/mnt/c/Users/{{myUserName}}/Ansible-R80-Scripts/GoldenImageScan.retry

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=1
```

**Comment by Martin4Kansas** [comment]
It appears that the module is converting the "'" character into /" and that's causing it to fail.

**Comment by chkp-rdecker** [comment]
I'm not sure.
Please open the api.elg file on your management and see what does the your latest run-script command execution reports.

**Comment by Martin4Kansas** [comment]
I don't have a api.elg file on the management.  If you look at the other parameters name and targets they are both unicode strings that look like u'string'  and not like u\"string\".  I think that this has to be the issue.

**Comment by Martin4Kansas** [comment]
This same command works when making a call in Postman.

**Comment by JonTheNiceGuy** [comment]
I'm not sure if you need to escape the quotes, as you're wrapping them in a single quote. Try this instead:

````yaml
---
- hosts: localhost
  vars_files:
  - r80_vars.yml
  tasks:  
  - name: Login
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        port: 8443
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response

  - name: Create output file
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: Create output file
        script: touch output.txt
        targets: "{{targets}}"
      session-data: "{{login_response}}"
      
  - name: Golden Image
    check_point_mgmt:
      command: run-script
      parameters:
        script-name: Golden Image
        script: 'clish -c "show core-dump status" &>> output.txt'
        targets: "{{targets}}"
      session-data: "{{login_response}}"
    #Core dumps enabled
````

This is just a guess, I've not tried executing this command myself, but Ansible is pretty good at wrapping and unwrapping strings as they're required.

**Comment by chkp-rdecker** [comment]
you can find the api.elg file on your management server inside "$MDS_FWDIR/logs" folder.
please run again the script, navigate to the end of log file and paste here all the related content to "run-script" command.

**Comment by Martin4Kansas** [comment]
.bash_history
.bash_logout
.bash_profile
.bashrc
.clish_history
.mgmt_cli/
.psql_history
.ssh/
2018.07.12_14-05-24_api_data_apilog_txt.tgz
last_dump.log
These are the only files that I can access on the management server.  There is no "$MDS_FWDIR/logs" folder.
Again, the command works when using Postman it has to be something with the escape quotes.  I'm going to try Jon's suggestion now although your documentation specifically states that I should use the format that I tried.

**Comment by chkp-rdecker** [comment]
No, no, you are apparently searching on your ansible server, you should search on Check Point Management Server - the "{{mgmt_server}}" of your login command...

**Comment by chkp-rdecker** [comment]
any news?

**Comment by chkp-rdecker** [comment]
Closed as no input was provided during last month.

**Comment by s14tish** [comment]
Hi Team,

Am facing the issue while running below playbook. Please help on this.

---
- hosts: "localhost"
  gather_facts: no
  connection: local

  vars:
   - name: "mgmt_username"
     mgmt_username: "xxxxxx"
   - name: "mgmt_password"
     mgmt_password: "xxxxxxxx"
   - name: "auth_pass"
     auth_pass: "xxxxxxxxxxxxx"
   - name: "mgmt_server"
     mgmt_server: "xxxxxxxx"

  tasks:
   - name: "Login"
     check_point_mgmt:
       command: login
       parameters:
         username: "{{mgmt_user}}"
         password: "{{mgmt_password}}"
         management: "{{mgmt_server}}"
         port: 8443
       fingerprint: "{{mgmt_fingerprint}}"
     register: login_response

   - name: "Create output file"
     check_point_mgmt:
       command: run-script
       parameters:
         script-name: "Create output file"
         script: "touch output.txt"
         targets: "{{targets}}"
       session-data: "{{login_response}}"

   - name: "Golden Image"
     check_point_mgmt:
       command: run-script
       parameters:
         script-name: "Golden Image"
         script: 'clish -c \"show core-dump status\" &>> output.txt'
         targets: "{{targets}}"
       session-data: "{{login_response}}"
     #Core dumps enabled




Error:

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/var/lib/awx/projects/Network-Team/checkpoint.yaml': line 17, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
   - name: "Login"
     ^ here


The error appears to have been in '/var/lib/awx/projects/Network-Team/checkpoint.yaml': line 17, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
   - name: "Login"
     ^ here
